function createParams()
    
    hvacParams = struct( ...
        'c', 1005, ...            % 空气的比热容 (J/kg·K)
        'rho', 1.205, ...         % 空气密度 (kg/m^3)
        'volumeRoom', 300, ...        % 房间体积 (m^3)
        'areaRoom', 100, ...        % 房间表面积 (m^2)
        'areaWindow', 10, ...       % 窗户面积 (m^2)
        'areaSurface', 120, ...           % 传热表面积（墙壁等）(m^2)
        'k', 0.6, ...             % 建筑外围护结构的传热系数 (W/m^2·K)
        'ventilationRate', 3, ...          % 空气交换率
        'epsilon', 2.1, ...       % 人员活动每平方米产生的热量 (W/m^2)
        'solarGainCoeff', 0.2, ... %
        'pRated', 3800, ...       % 空调的额定功率 (W)
        'pStandby', 30, ...         % 空调待机功率 (W)
        'tempOut', 35, ...          % 室外温度 (℃)
        'tempInd', 25 ...           % 室内初始温度 (℃)
    );

    loadsType = {'non_interruptible', 'non_interruptible', ...
                'non_interruptible', 'non_interruptible', ...
                'non_interruptible', 'uncontrollable'};

    loadsName = {'WashingMachine', 'DishWasher', 'WaterHeater', ...
                'ClothesDryer', 'oven', 'other'};

    loadsParams = arrayfun(@(type, name) struct( ...
        'loadType', type, ...
        'loadName', name), ...
        loadsType, loadsName);

    evParams = struct( ...
        'capRated', 60, ...           % 电池额定容量 60 kWh
        'pRated', 50, ...         % 最大充放电功率 50 kW
        'degradationCostRate', 0.1,... % 每充放电循环的退化成本 0.1
        'chargeEfficiency', 0.99, ...  % 充电效率 90%
        'dischargeEfficiency', 0.99 ... % 放电效率 90%
    );
    numHomes = 2;  % 家庭数量
    homeParamsArray = arrayfun(@(~) struct( ...
        'hvacParams', hvacParams, ...
        'loadsParams', loadsParams, ...
        'evParams', evParams ...
    ), 1:numHomes);
    pvParams = struct( ...
        'pRated', 13.7 ...
    );

    bessParams = struct( ...
        'capRated', 10, ...
        'pRated', 10, ...
        'chargeEfficiency', 0.99, ...
        'dischargeEfficiency', 0.99, ...
        'degradationRate', 0.1 ...
        );
    
    microCommGridParams = struct( ...
        'homeParamsArray', homeParamsArray', ...
        'pvParams', pvParams, ...
        'bessParams', bessParams ...
    );

    elecPriceArray = [7.8, 7.8, 7.8, 7.8, 7.8, 7.8, 7.8, ... 
            12.2, 12.2, 12.2, 12.2, 12.2, 12.2, 12.2, 12.2, 12.2,...
            28.6, 28.6, 28.6, 28.6, 28.6, ...
            12.2, 12.2, ...
            7.8 ...
    ];
    elecPriceArray = repelem(elecPriceArray', 6);
    
    timeLine = struct( ...
        'timeslotDuration', 600, ...
        'totalTimeslot', 2016, ...
        'currentTimeslot', 1 ...
    );
    
    save('.\01_src\config\modelConfig.mat', 'microCommGridParams', 'elecPriceArray', 'timeLine');

    stateDim = 6;
    actionDim = 2;
    ckpt_dir = './02_data/02_output/weightMatrix/';  % 模型保存目录
    actorParams = struct('alpha', 0.0001,...                     % 学习率
                         'stateDim', stateDim,...             % 状态空间维度
                         'actionDim', actionDim,...           % 动作空间维度
                         'fc1Dim', 400,...                     % 隐藏层1维度
                         'fc2Dim', 300);                       % 隐藏层2维度
    criticParams = struct('beta', 0.0001,...                    % 学习率
                          'stateDim', stateDim,...            % 状态空间维度
                          'actionDim', actionDim,...          % 动作空间维度
                          'fc1Dim', 400,...                    % 隐藏层1维度
                          'fc2Dim', 300);                      % 隐藏层2维度
    bufferParams = struct('maxSize', 1000000,...               % 学习率
                          'stateDim', stateDim,...            % 状态空间维度
                          'actionDim', actionDim,...          % 动作空间维度
                          'batchSize', 512);                   % 隐藏层2维度
    td3Params = struct(   'gamma', 0.98,...                     % 学习率
                          'actionNoise', 0.1,...               % 动作噪声
                          'policyNoise', 0.2,...               % 策略噪声
                          'policyNoiseClip', 0.4,...          % 策略噪声
                          'delayTime', 2,...                   % 评判次数
                          'ckptDir', ckpt_dir,...              % 参数保存目录
                          'stateDim', stateDim,...             % 状态空间维度
                          'actionDim', actionDim,...           % 动作空间维度
                          'actionSpaceLow', 0,...
                          'actionSpaceHigh', 3800,...
                          'actorParams', actorParams,...        % 策略网络参数
                          'criticParams', criticParams,...      % 评判网络参数
                          'bufferParams', bufferParams);        % 经验缓冲区参数
    save('.\01_src\config\td3Config.mat', 'td3Params');
end

